<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-23T02:44:39Z" name="Default suite" finished-at="2021-09-23T02:44:45Z" duration-ms="6027">
    <groups>
    </groups>
    <test started-at="2021-09-23T02:44:39Z" name="Default test" finished-at="2021-09-23T02:44:45Z" duration-ms="6027">
      <class name="testSuites.TeacherSuite">
        <test-method is-config="true" signature="setupDriver()[pri:0, instance:testSuites.TeacherSuite@16b2bb0c]" started-at="2021-09-22T22:44:39Z" name="setupDriver" finished-at="2021-09-22T22:44:44Z" duration-ms="5013" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method signature="login_Successful()[pri:0, instance:testSuites.TeacherSuite@16b2bb0c]" started-at="2021-09-22T22:44:44Z" name="login_Successful" finished-at="2021-09-22T22:44:45Z" duration-ms="997" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Step 1 failed. Login successful.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Step 1 failed. Login successful.
	at org.testng.Assert.fail(Assert.java:94)
	at testCases.Auth.login_Successful(Auth.java:36)
	at testSuites.TeacherSuite.login_Successful(TeacherSuite.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Successful -->
      </class> <!-- testSuites.TeacherSuite -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
